version: '3.8'

services:
  pansou:
    image: ghcr.io/fish2018/pansou-web:main
    container_name: pansou-app
    ports:
      - "80:80"
      - "443:443"
    environment:
      # 域名配置
      - DOMAIN=localhost
      # 后端服务配置
      - PANSOU_PORT=8888
      - PANSOU_HOST=127.0.0.1
      # 可选环境变量（PanSou后端支持的环境变量）
      # - CACHE_ENABLED=true
      # - CACHE_TTL=3600
      # - CACHE_MAX_SIZE=1000
      # - PLUGIN_TIMEOUT=30
      # - ASYNC_RESPONSE_TIMEOUT=60
      # - MAX_CONCURRENCY=200
      # - MAX_PAGES=30
      # - TG_BOT_TOKEN=your_bot_token
      # - SOCKS5_PROXY=socks5://proxy:1080
    volumes:
      # 数据持久化
      - pansou-data:/app/data
      - pansou-logs:/app/logs
      # SSL证书（可选）
      # - ./ssl:/app/data/ssl
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  pansou-data:
    driver: local
  pansou-logs:
    driver: local

# 网络配置（可选）
# networks:
#   pansou-network:
#     driver: bridge